# Generated by Django 4.1.4 on 2022-12-11 14:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import recharge.models


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AreaCircle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="CategoryPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Operator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("operator_name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.PositiveIntegerField(unique=True)),
                ("validity", models.PositiveIntegerField()),
                ("data", models.FloatField(max_length=5)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("MB", "MB"),
                            ("GB", "GB"),
                            ("MB/Day", "MB/Day"),
                            ("GB/Day", "GB/Day"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(max_length=250)),
                (
                    "plan_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="type",
                        to="recharge.categoryplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Recharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        max_length=10,
                        validators=[recharge.models.Recharge.validate_mobile_number],
                    ),
                ),
                ("recharge_date", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "circle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recharge.areacircle",
                        to_field="area",
                    ),
                ),
                (
                    "operator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recharge.operator",
                        to_field="operator_name",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plan_detail",
                        to="recharge.plan",
                        to_field="price",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        to_field="email",
                    ),
                ),
            ],
        ),
    ]
