# Generated by Django 4.1.4 on 2022-12-11 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0003_rename_area_areacircle_area_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="recharge",
            name="type",
            field=models.CharField(
                blank=True,
                choices=[("Prepaid", "Prepaid"), ("Postpaid", "Postpaid")],
                default="Prepaid",
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="plan_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="category_plan_type",
                to="recharge.categoryplan",
            ),
        ),
    ]
