# Generated by Django 4.1.4 on 2022-12-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0004_recharge_type_alter_plan_plan_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="sms",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
