# Generated by Django 4.1.4 on 2022-12-11 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0005_plan_sms"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="sms_type",
            field=models.CharField(
                choices=[("SMS", "SMS"), ("SMS/Day", "SMS/Day")],
                default=1,
                max_length=20,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="plan",
            name="sms",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
