# Generated by Django 4.1.4 on 2022-12-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0008_remove_plan_sms_remove_plan_sms_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="plan",
            name="validity_type",
        ),
        migrations.AddField(
            model_name="plan",
            name="validity_days",
            field=models.CharField(
                choices=[("Days", "Days")], default=1, max_length=20
            ),
            preserve_default=False,
        ),
    ]
