# Generated by Django 4.1.4 on 2022-12-11 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0009_remove_plan_validity_type_plan_validity_days"),
    ]

    operations = [
        migrations.RenameField(
            model_name="plan",
            old_name="validity_days",
            new_name="validity_type",
        ),
    ]
