# Generated by Django 4.1.4 on 2022-12-12 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0010_rename_validity_days_plan_validity_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="recharge",
            name="type",
        ),
    ]
