# Generated by Django 4.1.4 on 2022-12-15 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recharge", "0011_remove_recharge_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="operator",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="operator_based_plan",
                to="recharge.operator",
            ),
            preserve_default=False,
        ),
    ]
